package micdoodle8.mods.galacticraft.core.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.entity.Entity;

public class ModelLander extends ModelBase
{
    ModelRendererGC bodyMain1;
    ModelRendererGC bodyMain2;
    ModelRendererGC bodyAux1;
    ModelRendererGC bodyAux2;
    ModelRendererGC bodyAux3;
    ModelRendererGC bodyAux4;
    ModelRendererGC bodySupportMain1;
    ModelRendererGC bodySupportMain2;
    ModelRendererGC legStructureAux1e;
    ModelRendererGC footBaseg;
    ModelRendererGC legStructure1i;
    ModelRendererGC legBase1j;
    ModelRendererGC footJointk;
    ModelRendererGC footBasel;
    ModelRendererGC legBase1n;
    ModelRendererGC legStructureAux1s;
    ModelRendererGC legStructure1u;
    ModelRendererGC footJointv;
    ModelRendererGC footBasew;
    ModelRendererGC footBasex;
    ModelRendererGC legBase1z;
    ModelRendererGC legStructureAux1f;
    ModelRendererGC legStructure1g;
    ModelRendererGC footJointh;
    ModelRendererGC footBasei;
    ModelRendererGC footBasej;
    ModelRendererGC legBase1l;
    ModelRendererGC legStructureAux1q;
    ModelRendererGC legStructure1s;
    ModelRendererGC footJointt;
    ModelRendererGC footBaseu;
    ModelRendererGC footBasev;
    ModelRendererGC moduleMain1;
    ModelRendererGC moduleMain2;
    ModelRendererGC moduleMainDeco;
    ModelRendererGC moduleCore1;
    ModelRendererGC moduleCore2;
    ModelRendererGC moduleCore3;
    ModelRendererGC moduleAux1;
    ModelRendererGC moduleAux2;
    ModelRendererGC moduleAux3;
    ModelRendererGC moduleAux4;
    ModelRendererGC moduleAux5;
    ModelRendererGC moduleAux6;
    ModelRendererGC moduleAux7;
    ModelRendererGC moduleAux8;
    ModelRendererGC moduleThrusterBase1;
    ModelRendererGC moduleThrusterBase2;
    ModelRendererGC moduleThrusterBase3;
    ModelRendererGC moduleThrusterBase4;
    ModelRendererGC moduleThrusterBase5;
    ModelRendererGC moduleThrusterConeTop1;
    ModelRendererGC moduleThrusterConeTop2;
    ModelRendererGC moduleThrusterConeTop3;
    ModelRendererGC moduleThrusterConeBack1;
    ModelRendererGC moduleThrusterConeBack2;
    ModelRendererGC moduleThrusterConeBack3;
    ModelRendererGC moduleThrusterConeBot1;
    ModelRendererGC moduleThrusterConeBot2;
    ModelRendererGC moduleThrusterConeBot3;
    ModelRendererGC moduleThrusterConeFront1;
    ModelRendererGC moduleThrusterConeFront2;
    ModelRendererGC moduleThrusterConeFront3;

    public ModelLander()
    {
        this.textureWidth = 512;
        this.textureHeight = 512;

        this.bodyMain1 = new ModelRendererGC(this, 125, 128);
        this.bodyMain1.addBox(-24F, 0F, -24F, 48, 12, 48);
        this.bodyMain1.setRotationPoint(0F, 0F, 0F);
        this.bodyMain1.setTextureSize(512, 512);
        this.bodyMain1.mirror = true;
        this.setRotation(this.bodyMain1, 0F, -0.3926991F, 0F);
        this.bodyMain2 = new ModelRendererGC(this, 125, 128);
        this.bodyMain2.addBox(-24F, -0.1F, -24F, 48, 12, 48);
        this.bodyMain2.setRotationPoint(0F, 0F, 0F);
        this.bodyMain2.setTextureSize(512, 512);
        this.bodyMain2.mirror = true;
        this.setRotation(this.bodyMain2, 0F, 0.3926991F, 0F);
        this.bodyAux1 = new ModelRendererGC(this, 125, 192);
        this.bodyAux1.addBox(-13F, -5F, -34F, 26, 15, 34);
        this.bodyAux1.setRotationPoint(0F, 0F, 0F);
        this.bodyAux1.setTextureSize(512, 512);
        this.bodyAux1.mirror = true;
        this.setRotation(this.bodyAux1, 0.0698132F, 0.7853982F, 0F);
        this.bodyAux2 = new ModelRendererGC(this, 125, 192);
        this.bodyAux2.addBox(-13F, -5F, -34F, 26, 15, 34);
        this.bodyAux2.setRotationPoint(0F, 0F, 0F);
        this.bodyAux2.setTextureSize(512, 512);
        this.bodyAux2.mirror = true;
        this.setRotation(this.bodyAux2, 0.0698132F, -0.7853982F, 0F);
        this.bodyAux3 = new ModelRendererGC(this, 125, 192);
        this.bodyAux3.addBox(-13F, -5F, -34F, 26, 15, 34);
        this.bodyAux3.setRotationPoint(0F, 0F, 0F);
        this.bodyAux3.setTextureSize(512, 512);
        this.bodyAux3.mirror = true;
        this.setRotation(this.bodyAux3, 0.0698132F, -2.356194F, 0F);
        this.bodyAux4 = new ModelRendererGC(this, 125, 192);
        this.bodyAux4.addBox(-13F, -5F, -34F, 26, 15, 34);
        this.bodyAux4.setRotationPoint(0F, 0F, 0F);
        this.bodyAux4.setTextureSize(512, 512);
        this.bodyAux4.mirror = true;
        this.setRotation(this.bodyAux4, 0.0698132F, 2.356194F, 0F);
        this.bodySupportMain1 = new ModelRendererGC(this, 125, 243);
        this.bodySupportMain1.addBox(-19F, -7F, -19F, 38, 10, 38);
        this.bodySupportMain1.setRotationPoint(0F, 0F, 0F);
        this.bodySupportMain1.setTextureSize(512, 512);
        this.bodySupportMain1.mirror = true;
        this.setRotation(this.bodySupportMain1, 0F, 0F, 0F);
        this.bodySupportMain2 = new ModelRendererGC(this, 125, 293);
        this.bodySupportMain2.addBox(-12F, -15F, -12F, 24, 15, 24);
        this.bodySupportMain2.setRotationPoint(0F, 0F, 0F);
        this.bodySupportMain2.setTextureSize(512, 512);
        this.bodySupportMain2.mirror = true;
        this.setRotation(this.bodySupportMain2, 0F, 0F, 0F);
        this.legStructureAux1e = new ModelRendererGC(this, 0, 81);
        this.legStructureAux1e.addBox(-26F, 28F, -2F, 3, 24, 3);
        this.legStructureAux1e.setRotationPoint(0F, 0F, 0F);
        this.legStructureAux1e.setTextureSize(512, 512);
        this.legStructureAux1e.mirror = true;
        this.setRotation(this.legStructureAux1e, 0F, -2.356194F, 0.7330383F);
        this.footBaseg = new ModelRendererGC(this, 125, 81);
        this.footBaseg.addBox(-64F, 18.9F, -2F, 11, 6, 2);
        this.footBaseg.setRotationPoint(0F, 0F, 0F);
        this.footBaseg.setTextureSize(512, 512);
        this.footBaseg.mirror = true;
        this.setRotation(this.footBaseg, 0F, -2.356194F, 0F);
        this.legStructure1i = new ModelRendererGC(this, 0, 0);
        this.legStructure1i.addBox(-27F, 33F, -3F, 5, 14, 5);
        this.legStructure1i.setRotationPoint(0F, 0F, 0F);
        this.legStructure1i.setTextureSize(512, 512);
        this.legStructure1i.mirror = true;
        this.setRotation(this.legStructure1i, 0F, -2.356194F, 0.7330383F);
        this.legBase1j = new ModelRendererGC(this, 16, 81);
        this.legBase1j.addBox(-29F, 20F, -5F, 9, 10, 9);
        this.legBase1j.setRotationPoint(0F, 0F, 0F);
        this.legBase1j.setTextureSize(512, 512);
        this.legBase1j.mirror = true;
        this.setRotation(this.legBase1j, 0F, -2.356194F, 0.7330383F);
        this.footJointk = new ModelRendererGC(this, 64, 104);
        this.footJointk.addBox(-58F, 20F, -6.5F, 7, 5, 11);
        this.footJointk.setRotationPoint(0F, 0F, 0F);
        this.footJointk.setTextureSize(512, 512);
        this.footJointk.mirror = true;
        this.setRotation(this.footJointk, 0F, -2.356194F, 0F);
        this.footBasel = new ModelRendererGC(this, 64, 81);
        this.footBasel.addBox(-62F, 23F, -8.5F, 10, 2, 15);
        this.footBasel.setRotationPoint(0F, 0F, 0F);
        this.footBasel.setTextureSize(512, 512);
        this.footBasel.mirror = true;
        this.setRotation(this.footBasel, 0F, -2.356194F, 0F);
        this.legBase1n = new ModelRendererGC(this, 16, 81);
        this.legBase1n.addBox(-29F, 20F, -5F, 9, 10, 9);
        this.legBase1n.setRotationPoint(0F, 0F, 0F);
        this.legBase1n.setTextureSize(512, 512);
        this.legBase1n.mirror = true;
        this.setRotation(this.legBase1n, 0F, -0.7853982F, 0.7330383F);
        this.legStructureAux1s = new ModelRendererGC(this, 0, 81);
        this.legStructureAux1s.addBox(-26F, 28F, -2F, 3, 24, 3);
        this.legStructureAux1s.setRotationPoint(0F, 0F, 0F);
        this.legStructureAux1s.setTextureSize(512, 512);
        this.legStructureAux1s.mirror = true;
        this.setRotation(this.legStructureAux1s, 0F, -0.7853982F, 0.7330383F);
        this.legStructure1u = new ModelRendererGC(this, 0, 0);
        this.legStructure1u.addBox(-27F, 33F, -3F, 5, 14, 5);
        this.legStructure1u.setRotationPoint(0F, 0F, 0F);
        this.legStructure1u.setTextureSize(512, 512);
        this.legStructure1u.mirror = true;
        this.setRotation(this.legStructure1u, 0F, -0.7853982F, 0.7330383F);
        this.footJointv = new ModelRendererGC(this, 64, 104);
        this.footJointv.addBox(-58F, 20F, -6.5F, 7, 5, 11);
        this.footJointv.setRotationPoint(0F, 0F, 0F);
        this.footJointv.setTextureSize(512, 512);
        this.footJointv.mirror = true;
        this.setRotation(this.footJointv, 0F, -0.7853982F, 0F);
        this.footBasew = new ModelRendererGC(this, 64, 81);
        this.footBasew.addBox(-62F, 23F, -8.5F, 10, 2, 15);
        this.footBasew.setRotationPoint(0F, 0F, 0F);
        this.footBasew.setTextureSize(512, 512);
        this.footBasew.mirror = true;
        this.setRotation(this.footBasew, 0F, -0.7853982F, 0F);
        this.footBasex = new ModelRendererGC(this, 125, 81);
        this.footBasex.addBox(-64F, 18.9F, -2F, 11, 6, 2);
        this.footBasex.setRotationPoint(0F, 0F, 0F);
        this.footBasex.setTextureSize(512, 512);
        this.footBasex.mirror = true;
        this.setRotation(this.footBasex, 0F, -0.7853982F, 0F);
        this.legBase1z = new ModelRendererGC(this, 16, 81);
        this.legBase1z.addBox(-29F, 20F, -5F, 9, 10, 9);
        this.legBase1z.setRotationPoint(0F, 0F, 0F);
        this.legBase1z.setTextureSize(512, 512);
        this.legBase1z.mirror = true;
        this.setRotation(this.legBase1z, 0F, 0.7853982F, 0.7330383F);
        this.legStructureAux1f = new ModelRendererGC(this, 0, 81);
        this.legStructureAux1f.addBox(-26F, 28F, -2F, 3, 24, 3);
        this.legStructureAux1f.setRotationPoint(0F, 0F, 0F);
        this.legStructureAux1f.setTextureSize(512, 512);
        this.legStructureAux1f.mirror = true;
        this.setRotation(this.legStructureAux1f, 0F, 0.7853982F, 0.7330383F);
        this.legStructure1g = new ModelRendererGC(this, 0, 0);
        this.legStructure1g.addBox(-27F, 33F, -3F, 5, 14, 5);
        this.legStructure1g.setRotationPoint(0F, 0F, 0F);
        this.legStructure1g.setTextureSize(512, 512);
        this.legStructure1g.mirror = true;
        this.setRotation(this.legStructure1g, 0F, 0.7853982F, 0.7330383F);
        this.footJointh = new ModelRendererGC(this, 64, 104);
        this.footJointh.addBox(-58F, 20F, -6.5F, 7, 5, 11);
        this.footJointh.setRotationPoint(0F, 0F, 0F);
        this.footJointh.setTextureSize(512, 512);
        this.footJointh.mirror = true;
        this.setRotation(this.footJointh, 0F, 0.7853982F, 0F);
        this.footBasei = new ModelRendererGC(this, 64, 81);
        this.footBasei.addBox(-62F, 23F, -8.5F, 10, 2, 15);
        this.footBasei.setRotationPoint(0F, 0F, 0F);
        this.footBasei.setTextureSize(512, 512);
        this.footBasei.mirror = true;
        this.setRotation(this.footBasei, 0F, 0.7853982F, 0F);
        this.footBasej = new ModelRendererGC(this, 125, 81);
        this.footBasej.addBox(-64F, 18.9F, -2F, 11, 6, 2);
        this.footBasej.setRotationPoint(0F, 0F, 0F);
        this.footBasej.setTextureSize(512, 512);
        this.footBasej.mirror = true;
        this.setRotation(this.footBasej, 0F, 0.7853982F, 0F);
        this.legBase1l = new ModelRendererGC(this, 16, 81);
        this.legBase1l.addBox(-29F, 20F, -5F, 9, 10, 9);
        this.legBase1l.setRotationPoint(0F, 0F, 0F);
        this.legBase1l.setTextureSize(512, 512);
        this.legBase1l.mirror = true;
        this.setRotation(this.legBase1l, 0F, 2.356194F, 0.7330383F);
        this.legStructureAux1q = new ModelRendererGC(this, 0, 81);
        this.legStructureAux1q.addBox(-26F, 28F, -2F, 3, 24, 3);
        this.legStructureAux1q.setRotationPoint(0F, 0F, 0F);
        this.legStructureAux1q.setTextureSize(512, 512);
        this.legStructureAux1q.mirror = true;
        this.setRotation(this.legStructureAux1q, 0F, 2.356194F, 0.7330383F);
        this.legStructure1s = new ModelRendererGC(this, 0, 0);
        this.legStructure1s.addBox(-27F, 33F, -3F, 5, 14, 5);
        this.legStructure1s.setRotationPoint(0F, 0F, 0F);
        this.legStructure1s.setTextureSize(512, 512);
        this.legStructure1s.mirror = true;
        this.setRotation(this.legStructure1s, 0F, 2.356194F, 0.7330383F);
        this.footJointt = new ModelRendererGC(this, 64, 104);
        this.footJointt.addBox(-58F, 20F, -6.5F, 7, 5, 11);
        this.footJointt.setRotationPoint(0F, 0F, 0F);
        this.footJointt.setTextureSize(512, 512);
        this.footJointt.mirror = true;
        this.setRotation(this.footJointt, 0F, 2.356194F, 0F);
        this.footBaseu = new ModelRendererGC(this, 64, 81);
        this.footBaseu.addBox(-62F, 23F, -8.5F, 10, 2, 15);
        this.footBaseu.setRotationPoint(0F, 0F, 0F);
        this.footBaseu.setTextureSize(512, 512);
        this.footBaseu.mirror = true;
        this.setRotation(this.footBaseu, 0F, 2.356194F, 0F);
        this.footBasev = new ModelRendererGC(this, 125, 81);
        this.footBasev.addBox(-64F, 18.9F, -2F, 11, 6, 2);
        this.footBasev.setRotationPoint(0F, 0F, 0F);
        this.footBasev.setTextureSize(512, 512);
        this.footBasev.mirror = true;
        this.setRotation(this.footBasev, 0F, 2.356194F, 0F);
        this.moduleMain1 = new ModelRendererGC(this, 289, 166);
        this.moduleMain1.addBox(-6F, -44F, -16F, 32, 32, 32);
        this.moduleMain1.setRotationPoint(0F, 0F, 0F);
        this.moduleMain1.setTextureSize(512, 512);
        this.moduleMain1.mirror = true;
        this.setRotation(this.moduleMain1, 0F, 0F, 0F);
        this.moduleMain2 = new ModelRendererGC(this, 249, 234);
        this.moduleMain2.addBox(-16F, -30F, -13F, 32, 16, 26);
        this.moduleMain2.setRotationPoint(0F, 0F, 0F);
        this.moduleMain2.setTextureSize(512, 512);
        this.moduleMain2.mirror = true;
        this.setRotation(this.moduleMain2, 0F, 0F, 0F);
        this.moduleMainDeco = new ModelRendererGC(this, 70, 300);
        this.moduleMainDeco.addBox(16F, -46F, -20.9F, 5, 30, 37);
        this.moduleMainDeco.setRotationPoint(0F, 0F, 0F);
        this.moduleMainDeco.setTextureSize(512, 512);
        this.moduleMainDeco.mirror = true;
        this.setRotation(this.moduleMainDeco, 0F, 0F, 0F);
        this.moduleCore1 = new ModelRendererGC(this, 197, 293);
        this.moduleCore1.mirror = true;
        this.moduleCore1.addBox(-20F, -48F, -25F, 5, 36, 42);
        this.moduleCore1.setRotationPoint(0F, 0F, 0F);
        this.moduleCore1.setTextureSize(512, 512);
        this.moduleCore1.mirror = true;
        this.setRotation(this.moduleCore1, 0F, 0F, 0F);
        this.moduleCore1.mirror = false;
        this.moduleCore2 = new ModelRendererGC(this, 197, 293);
        this.moduleCore2.addBox(-30F, -48F, -25F, 5, 36, 42);
        this.moduleCore2.setRotationPoint(0F, 0F, 0F);
        this.moduleCore2.setTextureSize(512, 512);
        this.moduleCore2.mirror = true;
        this.setRotation(this.moduleCore2, 0F, 0F, 0F);
        this.moduleCore3 = new ModelRendererGC(this, 295, 300);
        this.moduleCore3.addBox(-25F, -44F, -21F, 5, 28, 34);
        this.moduleCore3.setRotationPoint(0F, 0F, 0F);
        this.moduleCore3.setTextureSize(512, 512);
        this.moduleCore3.mirror = true;
        this.setRotation(this.moduleCore3, 0F, 0F, 0F);
        this.moduleAux1 = new ModelRendererGC(this, 85, 238);
        this.moduleAux1.addBox(26F, -34F, -13F, 4, 16, 26);
        this.moduleAux1.setRotationPoint(0F, 0F, 0F);
        this.moduleAux1.setTextureSize(512, 512);
        this.moduleAux1.mirror = true;
        this.setRotation(this.moduleAux1, 0F, 0F, 0F);
        this.moduleAux2 = new ModelRendererGC(this, 0, 110);
        this.moduleAux2.addBox(26.1F, -60F, 9F, 1, 28, 1);
        this.moduleAux2.setRotationPoint(0F, 0F, 0F);
        this.moduleAux2.setTextureSize(512, 512);
        this.moduleAux2.mirror = true;
        this.setRotation(this.moduleAux2, 0F, 0F, 0F);
        this.moduleAux3 = new ModelRendererGC(this, 17, 110);
        this.moduleAux3.addBox(27F, -57F, -12F, 1, 23, 1);
        this.moduleAux3.setRotationPoint(0F, 0F, 0F);
        this.moduleAux3.setTextureSize(512, 512);
        this.moduleAux3.mirror = true;
        this.setRotation(this.moduleAux3, 0F, 0F, 0F);
        this.moduleAux4 = new ModelRendererGC(this, 5, 110);
        this.moduleAux4.addBox(28F, -48F, -8F, 1, 14, 1);
        this.moduleAux4.setRotationPoint(0F, 0F, 0F);
        this.moduleAux4.setTextureSize(512, 512);
        this.moduleAux4.mirror = true;
        this.setRotation(this.moduleAux4, 0F, 0F, 0F);
        this.moduleAux5 = new ModelRendererGC(this, 5, 110);
        this.moduleAux5.addBox(28F, -48F, -6F, 1, 14, 1);
        this.moduleAux5.setRotationPoint(0F, 0F, 0F);
        this.moduleAux5.setTextureSize(512, 512);
        this.moduleAux5.mirror = true;
        this.setRotation(this.moduleAux5, 0F, 0F, 0F);
        this.moduleAux6 = new ModelRendererGC(this, 5, 110);
        this.moduleAux6.addBox(28F, -48F, -4F, 1, 14, 1);
        this.moduleAux6.setRotationPoint(0F, 0F, 0F);
        this.moduleAux6.setTextureSize(512, 512);
        this.moduleAux6.mirror = true;
        this.setRotation(this.moduleAux6, 0F, 0F, 0F);
        this.moduleAux7 = new ModelRendererGC(this, 11, 110);
        this.moduleAux7.addBox(27F, -53F, 2F, 1, 19, 1);
        this.moduleAux7.setRotationPoint(0F, 0F, 0F);
        this.moduleAux7.setTextureSize(512, 512);
        this.moduleAux7.mirror = true;
        this.setRotation(this.moduleAux7, 0F, 0F, 0F);
        this.moduleAux8 = new ModelRendererGC(this, 0, 110);
        this.moduleAux8.addBox(28.9F, -60F, 9F, 1, 28, 1);
        this.moduleAux8.setRotationPoint(0F, 0F, 0F);
        this.moduleAux8.setTextureSize(512, 512);
        this.moduleAux8.mirror = true;
        this.setRotation(this.moduleAux8, 0F, 0F, 0F);
        this.moduleThrusterBase1 = new ModelRendererGC(this, 21, 19);
        this.moduleThrusterBase1.addBox(30F, -28F, -5F, 3, 6, 10);
        this.moduleThrusterBase1.setRotationPoint(0F, 0F, 0F);
        this.moduleThrusterBase1.setTextureSize(512, 512);
        this.moduleThrusterBase1.mirror = true;
        this.setRotation(this.moduleThrusterBase1, 0F, 0F, 0F);
        this.moduleThrusterBase2 = new ModelRendererGC(this, 50, 0);
        this.moduleThrusterBase2.addBox(5F, -39F, -5F, 3, 5, 10);
        this.moduleThrusterBase2.setRotationPoint(0F, 0F, 0F);
        this.moduleThrusterBase2.setTextureSize(512, 512);
        this.moduleThrusterBase2.mirror = true;
        this.setRotation(this.moduleThrusterBase2, 0F, 0F, 0.7853982F);
        this.moduleThrusterBase3 = new ModelRendererGC(this, 50, 0);
        this.moduleThrusterBase3.addBox(-43F, -4F, -5F, 3, 6, 10);
        this.moduleThrusterBase3.setRotationPoint(0F, 0F, 0F);
        this.moduleThrusterBase3.setTextureSize(512, 512);
        this.moduleThrusterBase3.mirror = true;
        this.setRotation(this.moduleThrusterBase3, 0F, 0F, 2.356194F);
        this.moduleThrusterBase4 = new ModelRendererGC(this, 0, 23);
        this.moduleThrusterBase4.addBox(24F, -28F, 13.7F, 3, 6, 6);
        this.moduleThrusterBase4.setRotationPoint(0F, 0F, 0F);
        this.moduleThrusterBase4.setTextureSize(512, 512);
        this.moduleThrusterBase4.mirror = true;
        this.setRotation(this.moduleThrusterBase4, 0F, 0.7853982F, 0F);
        this.moduleThrusterBase5 = new ModelRendererGC(this, 0, 23);
        this.moduleThrusterBase5.mirror = true;
        this.moduleThrusterBase5.addBox(24F, -28F, -19.5F, 3, 6, 6);
        this.moduleThrusterBase5.setRotationPoint(0F, 0F, 0F);
        this.moduleThrusterBase5.setTextureSize(512, 512);
        this.moduleThrusterBase5.mirror = true;
        this.setRotation(this.moduleThrusterBase5, 0F, -0.7853982F, 0F);
        this.moduleThrusterBase5.mirror = false;
        this.moduleThrusterConeTop1 = new ModelRendererGC(this, 40, 9);
        this.moduleThrusterConeTop1.addBox(-44F, -3F, -1F, 1, 2, 2);
        this.moduleThrusterConeTop1.setRotationPoint(0F, 0F, 0F);
        this.moduleThrusterConeTop1.setTextureSize(512, 512);
        this.moduleThrusterConeTop1.mirror = true;
        this.setRotation(this.moduleThrusterConeTop1, 0F, 0F, 2.356194F);
        this.moduleThrusterConeTop2 = new ModelRendererGC(this, 30, 9);
        this.moduleThrusterConeTop2.addBox(-45F, -3.5F, -1.5F, 1, 3, 3);
        this.moduleThrusterConeTop2.setRotationPoint(0F, 0F, 0F);
        this.moduleThrusterConeTop2.setTextureSize(512, 512);
        this.moduleThrusterConeTop2.mirror = true;
        this.setRotation(this.moduleThrusterConeTop2, 0F, 0F, 2.356194F);
        this.moduleThrusterConeTop3 = new ModelRendererGC(this, 29, 0);
        this.moduleThrusterConeTop3.addBox(-46F, -4F, -2F, 1, 4, 4);
        this.moduleThrusterConeTop3.setRotationPoint(0F, 0F, 0F);
        this.moduleThrusterConeTop3.setTextureSize(512, 512);
        this.moduleThrusterConeTop3.mirror = true;
        this.setRotation(this.moduleThrusterConeTop3, 0F, 0F, 2.356194F);
        this.moduleThrusterConeBack1 = new ModelRendererGC(this, 40, 9);
        this.moduleThrusterConeBack1.addBox(27F, -26F, -18.5F, 1, 2, 2);
        this.moduleThrusterConeBack1.setRotationPoint(0F, 0F, 0F);
        this.moduleThrusterConeBack1.setTextureSize(512, 512);
        this.moduleThrusterConeBack1.mirror = true;
        this.setRotation(this.moduleThrusterConeBack1, 0F, -0.7853982F, 0F);
        this.moduleThrusterConeBack2 = new ModelRendererGC(this, 30, 9);
        this.moduleThrusterConeBack2.addBox(28F, -26.5F, -19F, 1, 3, 3);
        this.moduleThrusterConeBack2.setRotationPoint(0F, 0F, 0F);
        this.moduleThrusterConeBack2.setTextureSize(512, 512);
        this.moduleThrusterConeBack2.mirror = true;
        this.setRotation(this.moduleThrusterConeBack2, 0F, -0.7853982F, 0F);
        this.moduleThrusterConeBack3 = new ModelRendererGC(this, 29, 0);
        this.moduleThrusterConeBack3.addBox(29F, -27F, -19.5F, 1, 4, 4);
        this.moduleThrusterConeBack3.setRotationPoint(0F, 0F, 0F);
        this.moduleThrusterConeBack3.setTextureSize(512, 512);
        this.moduleThrusterConeBack3.mirror = true;
        this.setRotation(this.moduleThrusterConeBack3, 0F, -0.7853982F, 0F);
        this.moduleThrusterConeBot1 = new ModelRendererGC(this, 40, 9);
        this.moduleThrusterConeBot1.addBox(8F, -38F, -1F, 1, 2, 2);
        this.moduleThrusterConeBot1.setRotationPoint(0F, 0F, 0F);
        this.moduleThrusterConeBot1.setTextureSize(512, 512);
        this.moduleThrusterConeBot1.mirror = true;
        this.setRotation(this.moduleThrusterConeBot1, 0F, 0F, 0.7853982F);
        this.moduleThrusterConeBot2 = new ModelRendererGC(this, 30, 9);
        this.moduleThrusterConeBot2.addBox(9F, -38.5F, -1.5F, 1, 3, 3);
        this.moduleThrusterConeBot2.setRotationPoint(0F, 0F, 0F);
        this.moduleThrusterConeBot2.setTextureSize(512, 512);
        this.moduleThrusterConeBot2.mirror = true;
        this.setRotation(this.moduleThrusterConeBot2, 0F, 0F, 0.7853982F);
        this.moduleThrusterConeBot3 = new ModelRendererGC(this, 29, 0);
        this.moduleThrusterConeBot3.addBox(10F, -39F, -2F, 1, 4, 4);
        this.moduleThrusterConeBot3.setRotationPoint(0F, 0F, 0F);
        this.moduleThrusterConeBot3.setTextureSize(512, 512);
        this.moduleThrusterConeBot3.mirror = true;
        this.setRotation(this.moduleThrusterConeBot3, 0F, 0F, 0.7853982F);
        this.moduleThrusterConeFront1 = new ModelRendererGC(this, 40, 9);
        this.moduleThrusterConeFront1.addBox(27F, -26F, 16.5F, 1, 2, 2);
        this.moduleThrusterConeFront1.setRotationPoint(0F, 0F, 0F);
        this.moduleThrusterConeFront1.setTextureSize(512, 512);
        this.moduleThrusterConeFront1.mirror = true;
        this.setRotation(this.moduleThrusterConeFront1, 0F, 0.7853982F, 0F);
        this.moduleThrusterConeFront2 = new ModelRendererGC(this, 30, 9);
        this.moduleThrusterConeFront2.addBox(28F, -26.5F, 16F, 1, 3, 3);
        this.moduleThrusterConeFront2.setRotationPoint(0F, 0F, 0F);
        this.moduleThrusterConeFront2.setTextureSize(512, 512);
        this.moduleThrusterConeFront2.mirror = true;
        this.setRotation(this.moduleThrusterConeFront2, 0F, 0.7853982F, 0F);
        this.moduleThrusterConeFront3 = new ModelRendererGC(this, 29, 0);
        this.moduleThrusterConeFront3.addBox(29F, -27F, 15.5F, 1, 4, 4);
        this.moduleThrusterConeFront3.setRotationPoint(0F, 0F, 0F);
        this.moduleThrusterConeFront3.setTextureSize(512, 512);
        this.moduleThrusterConeFront3.mirror = true;
        this.setRotation(this.moduleThrusterConeFront3, 0F, 0.7853982F, 0F);
    }

    @Override
    public void render(Entity entity, float par2, float par3, float par4, float par5, float par6, float par7)
    {
        super.render(entity, par2, par3, par4, par5, par6, par7);
        this.setRotationAngles(par2, par3, par4, par5, par6, par7, entity);
        this.bodyMain1.render(par7);
        this.bodyMain2.render(par7);
        this.bodyAux1.render(par7);
        this.bodyAux2.render(par7);
        this.bodyAux3.render(par7);
        this.bodyAux4.render(par7);
        this.bodySupportMain1.render(par7);
        this.bodySupportMain2.render(par7);
        this.legStructureAux1e.render(par7);
        this.footBaseg.render(par7);
        this.legStructure1i.render(par7);
        this.legBase1j.render(par7);
        this.footJointk.render(par7);
        this.footBasel.render(par7);
        this.legBase1n.render(par7);
        this.legStructureAux1s.render(par7);
        this.legStructure1u.render(par7);
        this.footJointv.render(par7);
        this.footBasew.render(par7);
        this.footBasex.render(par7);
        this.legBase1z.render(par7);
        this.legStructureAux1f.render(par7);
        this.legStructure1g.render(par7);
        this.footJointh.render(par7);
        this.footBasei.render(par7);
        this.footBasej.render(par7);
        this.legBase1l.render(par7);
        this.legStructureAux1q.render(par7);
        this.legStructure1s.render(par7);
        this.footJointt.render(par7);
        this.footBaseu.render(par7);
        this.footBasev.render(par7);
        this.moduleMain1.render(par7);
        this.moduleMain2.render(par7);
        this.moduleMainDeco.render(par7);
        this.moduleCore1.render(par7);
        this.moduleCore2.render(par7);
        this.moduleCore3.render(par7);
        this.moduleAux1.render(par7);
        this.moduleAux2.render(par7);
        this.moduleAux3.render(par7);
        this.moduleAux4.render(par7);
        this.moduleAux5.render(par7);
        this.moduleAux6.render(par7);
        this.moduleAux7.render(par7);
        this.moduleAux8.render(par7);
        this.moduleThrusterBase1.render(par7);
        this.moduleThrusterBase2.render(par7);
        this.moduleThrusterBase3.render(par7);
        this.moduleThrusterBase4.render(par7);
        this.moduleThrusterBase5.render(par7);
        this.moduleThrusterConeTop1.render(par7);
        this.moduleThrusterConeTop2.render(par7);
        this.moduleThrusterConeTop3.render(par7);
        this.moduleThrusterConeBack1.render(par7);
        this.moduleThrusterConeBack2.render(par7);
        this.moduleThrusterConeBack3.render(par7);
        this.moduleThrusterConeBot1.render(par7);
        this.moduleThrusterConeBot2.render(par7);
        this.moduleThrusterConeBot3.render(par7);
        this.moduleThrusterConeFront1.render(par7);
        this.moduleThrusterConeFront2.render(par7);
        this.moduleThrusterConeFront3.render(par7);
    }

    private void setRotation(ModelRendererGC model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
}
